language: go
go:
- 1.5
install:
- go get github.com/spf13/hugo
script: hugo -t hugo-shadows
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: shadows.ajbourg.com
  region: us-west-2
  local-dir: public
  skip_cleanup: true
  on:
    repo: icebourg/shadows.ajbourg.com
